config/routes.rb
Rails.application.routes.draw do
  	devise_for :users
	resources :albums do
		collection { post :searchByTag}
		resources :photos 
	end
	root 'home#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :photos,  :dependent => :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :album
	has_many :tags
	accepts_nested_attributes_for :tags
	has_attached_file :image
	validates_attachment :image,
    	content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	before_action :find_album, only: [:show, :edit, :destroy, :find_photo, :searchByTag]
	before_action :find_photo, only: [ :searchByTag]
	def index
		@albums = Album.all
	end

	def show

		@photos= @album.photos
	end

	def new
		@album = Album.new
	end

	def create
		
		@album = Album.new(album_params)
	
		if @album.save
			
			redirect_to albums_path
		else
			render 'new'
		end
	end
	
	def destroy
	 @album = Album.find(params[:id])
     @album.destroy
     redirect_to albums_path, notice:  "The album #{@album.name} has been deleted."
	end

	def searchByTag
	
		@tags= Tag.where(:text=>params[:search])

	
	end

	private
	
	def  find_album
	
		@album =Album.find(params[:id])
	end

	def find_photo
			
		@photo=Photo.find(params[:id])
	end
	
	def album_params
		params.require(:album).permit(:name, :description)
	end
end

app/controllers/application_controller.rb
	class ApplicationController < ActionController::Base
  		before_action :authenticate_user!
		protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :find_album, only: [:show, :edit, :update, :destroy]

	def index
    @photos=Photo.where(:album_id => params[:album_id])
 	end

  def new
   	@photo = Photo.new
  end

  def create
    @album = Album.find(params[:album_id])
   	@photo = @album.photos.new(photo_params)
    	if @photo.save
       
        @photo.tags.create(tag_params[:text].split(",").map{ |i| { :text => i.strip } }
)
     
  		  flash[:success] = "The photo was added!"
   		  redirect_to  album_photo_path(@album, @photo), notice: "The photo was added!"
    	else
     		render 'new'
      end
  end

  def show
    @photo =Photo.find(params[:id])
  end
    
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to album_path(@album, @photo), notice:  "The photo #{@photo.title} has been deleted."
  end

  private

  def photo_params
  
    params.require(:photo).permit(:image, :title)
  end
  def tag_params
 
  	params.require(:photo).permit(:text)
  end

  def find_album
    @album=Photo.find(params[:id]).album_id
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		debugger
		@tags=Tag.where(:photo_id => params[:photo_id])
		debugger

	 end

	 def new 

	 	@tag=Tag.new

	 end

	 def show
	 	debugger


	 end
	 	
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/albums/index.html.erb
<br>
  <%= link_to "Create a new album", controller: "albums", action: "new" %><br>
	<table>
 		<body>
        <th>Album name</th>
        <th>Description</th><br>
      	<% @albums.each do |album| %>
          <tr>
	          <td><%= album.name %> </td>
            <td> <%= album.description %> </td>
	          <td><%= link_to "show album", album_path(album) %></td>
	          <td><%= link_to "delete album",  album_path(album),method: :delete,
              	data: { confirm: 'Are you sure?' } %></td>
        	</tr>
   	  	<% end %>
    </body>
  </table>

 

app/views/albums/new.html.erb
<%= form_tag("/albums", method: "post") do %>
	<h1><i>New Album</i></h1>
	Enter Album Name
	<%= text_field(:album, :name) %><br>
	Description
	<%= text_field(:album, :description) %><br>
	<%= submit_tag("Create Albums") %>
<% end %>

app/views/albums/searchByTag.html.erb
<table>
 	<body>
    	<th>Tag name</th>
      	<% @tags.each do |tag| %>
        	<tr>
	            <%if tag.photo.present? %>
		            <% if tag.photo.album_id == params[:id].to_i %>
		            	<td><%= tag.text %> </td>
		            	<td><%= link_to "show photo",album_photo_path(tag.photo.album_id,tag.photo_id)%></td>
		            <% end %>
		        <% end %>    
	       	</tr>
   	  	<% end %>
    </body>
</table>

app/views/albums/show.html.erb
 <%= form_tag(:controller => "albums", :action => "searchByTag", :id =>@album) do %>  
  Enter Tag Name
  <%= text_field_tag(:search) %><br />  
  <%= submit_tag("Search") %>  
<% end %>
</table>
<div class="page-header"><h1>Photos</h1></div>
<%= link_to "New Photo",  new_album_photo_path(@album) %><br>

<table>
 		<body>
        <th>Title</th>
        <th>image_file_name:</th><br>
      	<% @photos.each do |photo| %>
          <tr>
	          <td><%= photo.title %> </td>
            <td><%= photo.image_file_name %> </td>
            <td><%= link_to "Show Photo",  album_photo_path(@album,photo.id) %></td>

        	</tr>
   	  	<% end %>
    </body>
</table>



 

app/views/home/index.html.erb
<h1><%= link_to 'Open Album', controller: "albums", action: "index" %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Project</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	</head>
	<body>
		<p class="test">
		<% if user_signed_in? %>
			  Logged in as <strong><%= current_user.email %></strong>.
			  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'test' %> |
			  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'test'  %>
		<% else %>
			  <%= link_to "Sign up", new_user_registration_path, :class => 'test'  %> |
			  <%= link_to "Login", new_user_session_path, :class => 'test'  %>
		<% end %>

		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%= yield %>
	</body>
</html>

 <!-- <!DOCTYPE html>
<html>
   
   <head>
      <title>Tutorialspoint</title>
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
   </head>
   
   <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
   </body>

</html> -->

app/views/photos/_photo.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
  </div>
  <div class="media-body">

    <h4 class="media-heading"><%= photo.title %></h4>

  </div>
</div>

app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<%= render @photos %>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo, :url => album_photos_path , :method => :post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class ="form-group">
    <%= f.label :Tagname %>
    <input type="text" name="photo[text]" class='form-control'>
  </div> 
  
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
  <%= link_to 'Back', :back %>
<% end %>

app/views/photos/show.html.erb
<br>
<%= link_to 'Back', :back %>
<%= link_to "delete photo",  album_photo_path, :method =>"DELETE", 
              	data: { confirm: 'Are you sure?' } %>


<div class="page-header"><h1>Photos</h1></div>
	
<%= render @photo %>

app/views/shared/_error.html.erb
% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/index.html.erb
<h1>index</h1>
<table>
 	<body>
        <th>Tag Name</th>
        <% @tags.each do |t| %>
         <tr>
	        <td><%= t.text %> </td>
	        <td><%= link_to "Show Photo",  album_photo_tag_path(@album,@photo,@tags) %></td>
       	<% end %>
    </body>
</table>

app/views/tags/show.html.erb
<table>
 	<body>
    	<th>Tag name</th>
      	<% @tags.each do |t| %>
        	<tr>
	            <td><%= tag.name %> </td>
	            <td><%= link_to "show photo"%></td>
	       	</tr>
   	  	<% end %>
    </body>
</table>